== Becoming a Bitcoin Professional – A Guide to the CBP Exam ==
        

----



== Study Overview ==

The main topics of this course will consist of the following topics:

*History of Money and Ledger-based Economics
*Basic Cryptography
*Bitcoin Basics
*Mining
*Wallets, Clients and Key Management
*Bitcoin Commerce
*History of Money and Ledger-Based Economics


----


== History of Money and Ledger-based Economics ==
This section will cover the following:

*Centralized Ledgers
*Functions of Currency
*Distributed Consensus
*History of Bitcoin
*Price Derivation

=== Centralized Ledgers ===
Ledg·er – noun
– a book or other collection of financial accounts of a particular type.

A ledger is a system by which you are able to record and total monetary transactions by accounts with debits and credits, including a beginning monetary balance and ending monetary balance for each account.

A centralized ledger is specifically a ledger that is held and managed by a governing party, such as a single trusted person, company or 3rd party, or government.

For example, your bank is managing a centralized ledger for your account, and the accounts of other customers and businesses.

=== Functions of Currency ===

There are three well known functions of currency:

'''Measure of value / Unit of account'''

A unit of account (in economics) is a standard measurement of the market value of goods, services, and other transactions. It’s a measure of relative worth. Money acts as a standard measure and common denomination of trade. It is necessary for efficient accounting systems.

'''Store of value'''

To act as a store of value, a money must be able to be reliably saved, stored, and retrieved – and be predictably usable as a medium of exchange when it is retrieved. The value of the money must also remain stable over time. Some have argued that inflation, by reducing the value of money, diminishes the ability of the money to function as a store of value.

'''Medium of exchange'''

When money is used to intermediate the exchange of goods and services, it is performing a function as a medium of exchange. It thereby avoids the inefficiencies of a barter system, such as the “coincidence of wants” problem. Money’s most important usage is as a method for comparing the values of dissimilar objects.


=== History of Bitcoin ===

*Bitcoin was created by an unknown person that goes by the alias Satoshi Nakamoto.
*On August 18th 2008, the domain name bitcoin.org was registered.
*On October 31st 2008 a link to a paper authored by Satoshi Nakamoto titled Bitcoin: A Peer-to-Peer Electronic Cash System was posted to a cryptography mailing list. This paper is also known as the bitcoin whitepaper.
*On January, 3rd, 2009, the bitcoin network came into existence with the release of the first open source bitcoin client and the issuance of the first bitcoins, with Satoshi Nakamoto mining the first block of bitcoins ever (known as the genesis block), which had a reward of 50 bitcoins. Embedded in the coinbase of this block was the text: The Times 03/Jan/2009 Chancellor on brink of second bailout for banks.
*Programer Hal Finney downloaded the software the first day of release. On January 12th 2009 Finney received 10 bitcoins from Satoshi in the world’s first bitcoin transaction.
*July 2010 MtGox bitcoin exchange is launched.
*August 6th 2010 a major vulnerability in the bitcoin protocol was discovered.
*August 15th 2010 the vulnerability was exploited; over 184 billion bitcoins were generated in a transaction. Within hours, the transaction was spotted and erased from the transaction log after the bug was fixed and the network forked to an updated version of the bitcoin protocol. This was the only major security flaw found and exploited in bitcoin’s history.
*September 8 2010 Slush Pool mines the first block generated by a mining pool.
*2011 Other currencies based on bitcoin’s open source code are created.
*Satoshi Nakamoto is last heard from on April 23rd 2011.
*June 2011 Wikileaks starts accepting bitcoin donations.
*September 2012 the Bitcoin Foundation is launched with the goal to “accelerate the global growth of bitcoin through standardization, protection, and promotion of the open source protocol”.
*October 2012 Coinbase.com launches services to buy and sell bitcoin using bank transfers.
*March 2013 The Financial Crimes Enforcement Network (FinCEN) establishes regulatory guidelines for “decentralized virtual currencies” classifying certain activities involving selling bitcoin as a Money Service Business (or MSBs), that subject individuals and businesses to legal reporting obligations and registration with the department.
*May 15th 2013 US authorities seize accounts associated with MtGox. The company did not register as a money transmitter with FinCEN.
*October 2013 Robocoin and Bitcoiniacs launch the world’s first bitcoin ATM in Vancouver BC.
*February 2014 MtGox suspends trading and withdrawals. Later that month MtGox files for bankruptcy protection claiming 744,000 bitcoins had been stolen.
*June 2014 the network exceeded 100 petahash/sec
*Late 2014 a documentary film titled “The Rise and Rise of Bitcoin” is released.
*In January 2016, the network rate exceeded 1 exahash/sec
*March 2016, the Cabinet of Japan recognized virtual currencies like bitcoin as having a function similar to real money.


=== Price Derivation ===
The bitcoin price can fluctuate like any other currency value. There is no centralized exchange, just exchanges run by businesses. Each time bitcoin changes ownership during a transaction between two parties, both must come to an agreement on its price. Since there is no centralized exchange, the price may vary based on supply and demand, as well as many other factors in the bitcoin ecosystem.


----




== Basic Cryptography ==
This section will cover the following:

*Terms and Definitions
*Hash Functions
*Symmetric and Asymmetric Encryption
*Digital Signatures
 


=== Terminology ===

Encryption is the process of turning a clear-text message ('''Plaintext''') into a data stream which looks like a meaningless and random sequence of bits ('''ciphertext''').

The process of turning ciphertext back into plaintext is called decryption.

Cryptography deals with making communications secure.

Cryptoanalysis deals with breaking ciphertext, that is, recovering plaintext without knowing the key.

Cryptology is a branch of mathematics which deals with both cryptography and cryptoanalysis.

A cryptographic algorithm, also known as a cipher, is a mathematical function which uses plaintext as the input and produces ciphertext as the output and vice versa.

All modern ciphers use keys together with plaintext as the input to produce ciphertext. The same or a different key is supplied to the decryption function to recover plaintext from ciphertext. The details of a cryptographic algorithm are usually made public. It is the key that the security of a modern cipher lies in, not the details of the cipher.

 

=== Symmetric Algorithms VS Asymmetric Algorithms ===

Symmetric algorithms:

*Uses the same key for encryption and decryption.
*Both the sender and receiver agree on a key before they can exchange messages securely.

Asymmetric Algorithms:     (Public-key algorithms)

*Uses two different keys (a '''key pair''') for encryption and decryption.
*The two keys are mathematically related, but is computationally infeasible to calculate one key from the other.
*“Public-key” can be made public without risking encryption.
*Anyone can use the public key to encrypt a message, but only the owner of the private key can decrypt it.

Some public-key algorithms such as RSA allow the process to work in the opposite direction as well: a message can be encrypted with a private key and decrypted with the corresponding public key. If Alice (or anyone else) can decrypt a message with Bob’s public key she knows that the message must have come from Bob because no one else has Bob’s private key. Digital signatures work this way.

 

=== Hash Functions ===
Hash Algorithms: MD4, MD5, SHA, SHA256

MD stands for Message Digest. MD5 is just an improved version of MD4.

SHA stands for Secure Hash Algorithm. It was developed by the NIST and NSA.

SHA is considered more secure than other algorithms.

SHA 256 is a more modern, more secure version of SHA.

A hash function is any function that can be used to map data of arbitrary size to data of fixed size. The values returned by a hash function are called hashes.

A cryptographic hash function allows one to easily verify that some input data maps to a given hash value, but if the input data is unknown, it is deliberately difficult to reconstruct it by knowing the stored hash value.

Even a slight change to input data should cause the hash value to change drastically.
